//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// File generated by the Visual Studio Command Table Compiler version 17.0.0.0
// Generation time: 2026年9月28日 14:51:01
namespace SvnChangelistView {
    using System;
    using System.Runtime.InteropServices;
    
    
    [System.Runtime.InteropServices.GuidAttribute(CommandGuids.guidSvnChangelistViewCmdSet)]
    internal sealed class guidSvnChangelistViewCmdSet {
        
        public const uint cmdIdBadge = 512u;
    }
    
    internal sealed class CommandGuids {
        
        public const string guidSvnChangelistViewCmdSet = "9d3f1a47-2e86-4c5b-a1d9-7c4b8e2f6a31";
        
        public const string guidSvnChangelistViewPackage = "8a5c2f31-4b7d-4e2a-9c1b-3f6d8a2e5c74";
    }
}
